"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 20:31:14.791155
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_key', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('source_epsg', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('recommended_k', sa.Integer(), nullable=True),
    sa.Column('available_k', sa.JSON(), nullable=True),
    sa.Column('current_run', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.String(), nullable=True),
    sa.Column('runs', sa.JSON(), nullable=True),
    sa.Column('share_hash', sa.String(), nullable=True),
    sa.Column('consent', sa.Integer(), nullable=False),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('pruned_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('log_path', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('project_id', 'celery_task_id', name='uq_jobs_project_task')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)

    op.create_table('orthos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('stem', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('crs', sa.String(), nullable=True),
    sa.Column('bands', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_orthos_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orthos'))
    )
    with op.batch_alter_table('orthos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orthos_project_id'), ['project_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('ortho_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('model_key', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('recommended_k', sa.Integer(), nullable=True),
    sa.Column('available_k', sa.JSON(), nullable=True),
    sa.Column('chosen_k', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ortho_id'], ['orthos.id'], name=op.f('fk_runs_ortho_id_orthos'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_runs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    sa.UniqueConstraint('project_id', 'number', name='uq_runs_project_number')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_ortho_id'), ['ortho_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_state'), ['state'], unique=False)

    op.create_table('cluster_labels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('chosen_k', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cluster_labels_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_cluster_labels_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster_labels'))
    )
    with op.batch_alter_table('cluster_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cluster_labels_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_labels_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cluster_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cluster_labels_run_id'))
        batch_op.drop_index(batch_op.f('ix_cluster_labels_project_id'))

    op.drop_table('cluster_labels')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_state'))
        batch_op.drop_index(batch_op.f('ix_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_runs_ortho_id'))

    op.drop_table('runs')
    with op.batch_alter_table('orthos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orthos_project_id'))

    op.drop_table('orthos')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_state'))

    op.drop_table('projects')
    # ### end Alembic commands ###
